### ISSUE TITLE
Docker image not committed

### ISSUE THREAD

**Issue by mconstant** [Markichu/akash-minecraft-ssh#1]
I was browsing the Docker image source and it looks like the version you made with ssh was not committed and pushed. Where is the source for how to build that image?

**Comment by Markichu** [comment]
Hi, sorry for the late reply.

The version with ssh can be found on dockerhub at [markichu/minecraft-server-ssh](https://hub.docker.com/r/markichu/minecraft-server-ssh). It is a bit out of date due to issues with the github actions on the repo.

The source for the docker image is located at [Markichu/docker-minecraft-server-ssh](https://github.com/Markichu/docker-minecraft-server-ssh). Building instructions are in the [BUILDING.md](https://github.com/Markichu/docker-minecraft-server-ssh/blob/master/BUILDING.md) file.
